"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { Product } from "@/lib/types";

type Cart = Record<string, number>;
type Who = "human" | "agent" | null;
type Step = "main" | "processing" | "success";

const money = (n: number) => `$${n.toFixed(2)}`;

function buildInvoicePDF(d: {
  invNo: string;
  orderId: string;
  date: string;
  owner: string;
  method: string;
  tokenKey: string;
  items: { name: string; qty: number; priceUsd: number }[];
  total: number;
}): Blob {
  const L: string[] = [];
  const ascii = (s: string) => String(s).replace(/[^\x20-\x7E]/g, "-");
  const pesc = (s: string) =>
    ascii(s).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
  const T = (t: string, x: number, y: number, size: number, bold: boolean) =>
    L.push(
      `BT /${bold ? "F2" : "F1"} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${pesc(t)}) Tj ET`
    );
  const LINE = (y: number) => L.push(`0.8 w 50 ${y} m 545 ${y} l S`);
  T("OPEN_MART", 50, 790, 22, true);
  T("TAX INVOICE", 50, 768, 11, false);
  T("INVOICE NO: " + d.invNo, 50, 740, 9, false);
  T("DATE: " + d.date, 50, 726, 9, false);
  T("ORDER: " + d.orderId, 50, 712, 9, false);
  T("STATUS: PAID", 455, 740, 9, true);
  LINE(700);
  T("BILL TO (OWNER NAME ONLY)", 50, 682, 8, true);
  T(d.owner, 50, 666, 13, true);
  LINE(650);
  T("ITEM", 50, 634, 8, true);
  T("QTY", 380, 634, 8, true);
  T("PRICE", 430, 634, 8, true);
  T("AMOUNT", 495, 634, 8, true);
  LINE(626);
  let y = 608;
  d.items.forEach((it) => {
    T(it.name, 50, y, 9, false);
    T(String(it.qty), 380, y, 9, false);
    T(money(it.priceUsd), 430, y, 9, false);
    T(money(it.priceUsd * it.qty), 495, y, 9, false);
    y -= 18;
  });
  LINE(y + 6);
  T("TOTAL", 430, y - 14, 11, true);
  T(money(d.total), 495, y - 14, 11, true);
  y -= 44;
  T("PAYMENT METHOD: " + d.method, 50, y, 9, false);
  T("TOKEN: " + d.tokenKey, 50, y - 14, 9, false);
  T("SETTLEMENT: MONAD TESTNET", 50, y - 28, 9, false);
  LINE(y - 44);
  T(
    "Generated by OPEN_MART - agent-ready storefront.",
    50,
    y - 60,
    7,
    false
  );
  const stream = L.join("\n");
  const objs: string[] = [];
  objs[1] = "<< /Type /Catalog /Pages 2 0 R >>";
  objs[2] = "<< /Type /Pages /Kids [3 0 R] /Count 1 >>";
  objs[3] =
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>";
  objs[4] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";
  objs[5] = "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>";
  objs[6] = `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;
  let pdf = "%PDF-1.4\n";
  const off = [0];
  for (let i = 1; i <= 6; i++) {
    off[i] = pdf.length;
    pdf += `${i} 0 obj\n${objs[i]}\nendobj\n`;
  }
  const xref = pdf.length;
  pdf += "xref\n0 7\n0000000000 65535 f \n";
  for (let i = 1; i <= 6; i++)
    pdf += `${String(off[i]).padStart(10, "0")} 00000 n \n`;
  pdf += `trailer\n<< /Size 7 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  return new Blob([pdf], { type: "application/pdf" });
}

export default function MerchantPage() {
  const [products, setProducts] = useState<Product[]>([]);
  const [cart, setCart] = useState<Cart>({});
  const [filter, setFilter] = useState("ALL");
  const [query, setQuery] = useState("");
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [coOpen, setCoOpen] = useState(false);
  const [who, setWho] = useState<Who>(null);
  const [step, setStep] = useState<Step>("main");
  const [tokenInput, setTokenInput] = useState("");
  const [tokenErr, setTokenErr] = useState("");
  const [ownerName, setOwnerName] = useState("");
  const [verifiedKey, setVerifiedKey] = useState("");
  const [humanName, setHumanName] = useState("Demo Shopper");
  const [successMeta, setSuccessMeta] = useState("");
  const [invId, setInvId] = useState("");
  const [invBlobUrl, setInvBlobUrl] = useState("");
  const [invDataUrl, setInvDataUrl] = useState("");
  const [orderId, setOrderId] = useState("");
  const [txHash, setTxHash] = useState("");
  const [testTokens, setTestTokens] = useState<
    { tokenString: string; amountLimitUsd: number }[]
  >([]);

  useEffect(() => {
    fetch("/api/products")
      .then((r) => r.json())
      .then((d) => setProducts(d.products || d || []))
      .catch(() => setProducts([]));
    fetch("/api/tokens")
      .then((r) => r.json())
      .then((d) => {
        const list = (d.tokens || d || []).filter(
          (t: { status: string }) => t.status === "active"
        );
        setTestTokens(
          list.slice(0, 4).map((t: { tokenString: string; amountLimitUsd: number }) => ({
            tokenString: t.tokenString,
            amountLimitUsd: t.amountLimitUsd,
          }))
        );
      })
      .catch(() => undefined);
  }, []);

  const filtered = useMemo(() => {
    return products.filter((p) => {
      if (filter !== "ALL" && p.category.toUpperCase() !== filter) return false;
      if (query && !p.name.toLowerCase().includes(query.toLowerCase()))
        return false;
      return true;
    });
  }, [products, filter, query]);

  const items = useMemo(() => {
    return Object.entries(cart)
      .map(([id, qty]) => {
        const p = products.find((x) => x.id === id);
        return p ? { ...p, qty } : null;
      })
      .filter(Boolean) as (Product & { qty: number })[];
  }, [cart, products]);

  const total = items.reduce((s, i) => s + i.priceUsd * i.qty, 0);
  const count = items.reduce((s, i) => s + i.qty, 0);

  const add = (id: string, q = 1) =>
    setCart((c) => ({ ...c, [id]: (c[id] || 0) + q }));

  const openCheckout = () => {
    if (!items.length) return;
    setDrawerOpen(false);
    setWho(null);
    setStep("main");
    setTokenErr("");
    setOwnerName("");
    setVerifiedKey("");
    setTokenInput("");
    setCoOpen(true);
  };

  const verifyToken = async (e: React.FormEvent) => {
    e.preventDefault();
    setTokenErr("");
    setOwnerName("");
    setVerifiedKey("");
    const key = tokenInput.trim().toUpperCase();
    // Use first cart item merchant/category for verify preview, or electronics default
    const sample = items[0];
    const res = await fetch("/api/tokens/verify", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        tokenString: key,
        merchant: sample?.merchant || "trusted-gadgets.example",
        category: sample?.category || "electronics",
        amountUsd: total,
      }),
    });
    const data = await res.json();
    if (!data.ok) {
      setTokenErr(`✕ ${data.error || "TOKEN NOT FOUND ON MONAD VAULT"}`);
      return;
    }
    setOwnerName(data.ownerName || "AUTHORIZED OWNER");
    setVerifiedKey(key);
  };

  const finishLocalInvoice = useCallback(
    (meta: { method: string; payer: string; tokenKey: string; orderId: string; tx?: string }) => {
      const invNo = "MP-2026-" + String(Math.floor(Math.random() * 900000) + 100000);
      const blob = buildInvoicePDF({
        invNo,
        orderId: meta.orderId,
        date: new Date().toISOString().slice(0, 10),
        owner: meta.payer,
        method: meta.method,
        tokenKey: meta.tokenKey,
        items: items.map((i) => ({
          name: i.name,
          qty: i.qty,
          priceUsd: i.priceUsd,
        })),
        total,
      });
      const blobUrl = URL.createObjectURL(blob);
      const reader = new FileReader();
      reader.onload = () => {
        setInvBlobUrl(blobUrl);
        setInvDataUrl(String(reader.result));
        setInvId(invNo + ".pdf");
        setOrderId(meta.orderId);
        setTxHash(meta.tx || "");
        setSuccessMeta(
          `ORDER ${meta.orderId}<br/>PAYER: ${meta.payer}<br/>METHOD: ${meta.method}<br/>AMOUNT: ${money(total)}${
            meta.tx ? `<br/>TX: ${meta.tx.slice(0, 12)}…` : ""
          }`
        );
        setStep("success");
        setCart({});
      };
      reader.readAsDataURL(blob);
    },
    [items, total]
  );

  const payHuman = async () => {
    setStep("processing");
    const first = items[0];
    const create = await fetch("/api/orders/create", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        productId: first.id,
        qty: first.qty,
        deliveryMethod: "online",
      }),
    }).then((r) => r.json());
    if (create.error) {
      setTokenErr(create.error);
      setStep("main");
      return;
    }
    const pay = await fetch(
      `/api/orders/${encodeURIComponent(create.order.id)}/pay`,
      {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        paymentMethod: "human_card",
        payerName: humanName,
      }),
    }).then((r) => r.json());
    setTimeout(() => {
      finishLocalInvoice({
        method: "HUMAN CARD",
        payer: (humanName || "GUEST").toUpperCase(),
        tokenKey: "—",
        orderId: create.order.id,
        tx: pay.invoice?.txHash,
      });
    }, 800);
  };

  const payAgent = async () => {
    if (!verifiedKey) return;
    setStep("processing");
    setTokenErr("");
    const first = items[0];
    if (!first) {
      setStep("main");
      setTokenErr("✕ CART EMPTY");
      return;
    }
    try {
      // Pay the first cart line (demo). Keep total ≤ token limit.
      const createRes = await fetch("/api/orders/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          productId: first.id,
          qty: first.qty,
          deliveryMethod: first.trusted ? "online" : "cod",
        }),
      });
      const create = await createRes.json();
      if (!createRes.ok || create.error) {
        throw new Error(create.error || "ORDER_CREATE_FAILED");
      }

      const payRes = await fetch(
        `/api/orders/${encodeURIComponent(create.order.id)}/pay`,
        {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          paymentMethod: first.trusted ? "agent_token" : "cod",
          tokenString: verifiedKey,
          payerName: ownerName,
        }),
      });
      const pay = await payRes.json();
      if (!payRes.ok || pay.error) {
        throw new Error(pay.error || "PAYMENT_FAILED");
      }

      finishLocalInvoice({
        method: first.trusted ? "AGENT TOKEN" : "COD",
        payer: ownerName,
        tokenKey: verifiedKey,
        orderId: create.order.id,
        tx: pay.invoice?.txHash || pay.txHash,
      });
    } catch (err) {
      setStep("main");
      setTokenErr(
        `✕ ${err instanceof Error ? err.message : "PAYMENT_FAILED"}`
      );
    }
  };

  const chips = ["ALL", "ELECTRONICS", "HOME", "APPAREL", "ACCESSORIES"];

  return (
    <div
      className="min-h-screen"
      style={{ background: "var(--paper)", color: "var(--ink)" }}
    >
      <header
        className="sticky top-0 z-40 flex items-center justify-between border-b-2 px-[3rem] py-[1.2rem] max-md:px-5"
        style={{
          borderColor: "var(--ink)",
          background: "var(--paper)",
        }}
      >
        <div
          className="mono text-[1.1rem] font-bold tracking-tight"
          style={{ letterSpacing: "-0.02em" }}
        >
          OPEN<span style={{ color: "var(--mart-accent)" }}>_</span>MART
        </div>
        <div className="flex items-center gap-6">
          <span
            className="mono text-[0.68rem] uppercase max-md:hidden"
            style={{
              letterSpacing: "0.15em",
              color: "var(--mart-muted)",
            }}
          >
            NO LOGIN · NO SIGNUP · AGENT-READY
          </span>
          <a
            href="/generate-token"
            className="mono text-[0.68rem] uppercase underline"
            style={{ letterSpacing: "0.1em", color: "var(--mart-muted)" }}
          >
            SattelR Console
          </a>
          <button
            type="button"
            onClick={() => setDrawerOpen(true)}
            className="mono flex items-center gap-2 border-2 px-5 py-3 text-[0.75rem] uppercase transition"
            style={{
              background: "var(--ink)",
              color: "var(--paper)",
              borderColor: "var(--ink)",
              letterSpacing: "0.12em",
              borderRadius: 2,
            }}
          >
            CART{" "}
            <span
              className="px-2 font-bold"
              style={{
                background: "var(--mart-accent)",
                color: "var(--ink)",
                borderRadius: 2,
              }}
            >
              {count}
            </span>
          </button>
        </div>
      </header>

      <section
        className="border-b-2 px-[3rem] pb-12 pt-[4.5rem] max-md:px-5"
        style={{ borderColor: "var(--ink)" }}
      >
        <h1
          className="font-black uppercase leading-[0.9]"
          style={{
            fontSize: "clamp(2.6rem,7.5vw,7rem)",
            letterSpacing: "-0.05em",
          }}
        >
          SHOP<span style={{ color: "var(--mart-accent)" }}>.</span>
          <br />
          AGENTS WELCOME
          <span style={{ color: "var(--mart-accent)" }}>.</span>
        </h1>
        <p
          className="mono mt-6 max-w-[70ch] text-[0.8rem] uppercase leading-loose"
          style={{ letterSpacing: "0.12em", color: "var(--mart-muted)" }}
        >
          Browse the catalog. Add to cart. At checkout choose HUMAN or AGENT.
          Agents paste a Monad access token — only the owner&apos;s name is
          revealed. Payment settles on Monad Testnet via SattelR vault.
        </p>
      </section>

      <div
        className="sticky z-30 flex flex-wrap items-center gap-4 border-b px-[3rem] py-5 max-md:px-5"
        style={{
          top: 63,
          borderColor: "var(--ink)",
          background: "var(--paper)",
        }}
      >
        <input
          className="mono min-w-[220px] flex-1 border-2 px-4 py-3 text-[0.85rem] outline-none"
          style={{
            background: "#fff",
            borderColor: "var(--ink)",
            borderRadius: 2,
          }}
          placeholder="SEARCH CATALOG…"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
        />
        <div className="flex flex-wrap gap-2">
          {chips.map((c) => (
            <button
              key={c}
              type="button"
              onClick={() => setFilter(c)}
              className="mono border-2 px-4 py-2 text-[0.7rem] uppercase transition"
              style={{
                letterSpacing: "0.1em",
                borderRadius: 2,
                borderColor: "var(--ink)",
                background:
                  filter === c ? "var(--mart-accent)" : "transparent",
                color: "var(--ink)",
                fontWeight: filter === c ? 700 : 400,
              }}
            >
              {c}
            </button>
          ))}
        </div>
      </div>

      <main
        className="grid border-l"
        style={{
          gridTemplateColumns: "repeat(auto-fill,minmax(240px,1fr))",
          borderColor: "var(--ink)",
        }}
      >
        {filtered.map((p, i) => (
          <div
            key={p.id}
            className="group flex flex-col gap-3 border-b border-r p-5 transition"
            style={{
              borderColor: "var(--ink)",
              background: "var(--paper)",
            }}
            onMouseEnter={(e) => {
              e.currentTarget.style.background = "var(--ink)";
              e.currentTarget.style.color = "var(--paper)";
            }}
            onMouseLeave={(e) => {
              e.currentTarget.style.background = "var(--paper)";
              e.currentTarget.style.color = "var(--ink)";
            }}
          >
            <div className="flex justify-between">
              <span
                className="mono text-[2.6rem] font-bold leading-none"
                style={{
                  color: "transparent",
                  WebkitTextStroke: "1px currentColor",
                }}
              >
                {String(i + 1).padStart(2, "0")}
              </span>
              <span
                className="mono text-[0.62rem] uppercase"
                style={{ letterSpacing: "0.15em", opacity: 0.7 }}
              >
                {p.category}
              </span>
            </div>
            <div className="min-h-[2.3em] text-[1.05rem] font-extrabold uppercase leading-tight">
              {p.name}
            </div>
            <div className="mono text-[0.7rem] opacity-70">
              ★ {p.rating} · {p.reviews.toLocaleString()} REVIEWS
              {p.trusted ? " · TRUSTED" : " · UNTRUSTED"}
            </div>
            <div className="mt-auto flex items-center justify-between gap-3">
              <span className="mono text-[1.05rem] font-bold">
                {money(p.priceUsd)}
              </span>
              <button
                type="button"
                onClick={() => add(p.id)}
                className="mono border-2 px-4 py-2 text-[0.7rem] font-bold uppercase transition group-hover:bg-[var(--mart-accent)]"
                style={{
                  background: "var(--ink)",
                  color: "var(--paper)",
                  borderColor: "var(--ink)",
                  letterSpacing: "0.12em",
                  borderRadius: 2,
                }}
              >
                ADD +
              </button>
            </div>
          </div>
        ))}
      </main>

      <footer
        className="mono flex flex-wrap justify-between gap-8 border-t-2 px-[3rem] py-10 text-[0.68rem] uppercase leading-loose max-md:px-5"
        style={{
          borderColor: "var(--ink)",
          color: "var(--mart-muted)",
          letterSpacing: "0.08em",
        }}
      >
        <div>
          <b style={{ color: "var(--ink)" }}>OPEN_MART</b> — AGENT-READY
          STOREFRONT
          <br />
          POWERED BY SATTELR · MONAD TESTNET
        </div>
        <div>
          AGENTS: USE{" "}
          <b style={{ color: "var(--ink)" }}>/api/products</b> +{" "}
          <b style={{ color: "var(--ink)" }}>/api/orders</b>
          <br />
          TOKEN CONSOLE → /generate-token
        </div>
      </footer>

      {/* Cart drawer */}
      <div
        className="fixed inset-0 z-[60] transition"
        style={{
          background: "rgba(20,20,20,.4)",
          opacity: drawerOpen ? 1 : 0,
          pointerEvents: drawerOpen ? "auto" : "none",
        }}
        onClick={() => setDrawerOpen(false)}
      />
      <aside
        className="fixed bottom-0 right-0 top-0 z-[70] flex w-[min(440px,100vw)] flex-col border-l-2 transition-transform duration-500"
        style={{
          background: "var(--paper)",
          borderColor: "var(--ink)",
          transform: drawerOpen ? "none" : "translateX(100%)",
        }}
      >
        <div
          className="flex items-center justify-between border-b-2 px-6 py-5"
          style={{ borderColor: "var(--ink)" }}
        >
          <h3 className="text-[1.2rem] font-black uppercase">Your Cart</h3>
          <button type="button" className="text-2xl" onClick={() => setDrawerOpen(false)}>
            ×
          </button>
        </div>
        <div className="flex-1 overflow-y-auto px-6 py-4">
          {!items.length ? (
            <div
              className="mono py-8 text-[0.8rem] uppercase"
              style={{ color: "var(--mart-muted)", letterSpacing: "0.12em" }}
            >
              CART EMPTY — ADD SOMETHING.
            </div>
          ) : (
            items.map((it) => (
              <div
                key={it.id}
                className="grid grid-cols-[1fr_auto] gap-2 border-b py-4"
                style={{ borderColor: "var(--ink)" }}
              >
                <div>
                  <div className="text-[0.9rem] font-bold uppercase">
                    {it.name}
                  </div>
                  <div
                    className="mono mt-1 text-[0.7rem]"
                    style={{ color: "var(--mart-muted)" }}
                  >
                    {it.category} · {money(it.priceUsd)} EA
                  </div>
                  <div className="mono mt-2 flex items-center gap-2 text-[0.85rem]">
                    <button
                      type="button"
                      className="h-[26px] w-[26px] border-2"
                      style={{ borderColor: "var(--ink)", borderRadius: 2 }}
                      onClick={() =>
                        setCart((c) => {
                          const n = { ...c };
                          n[it.id] = (n[it.id] || 0) - 1;
                          if (n[it.id] <= 0) delete n[it.id];
                          return n;
                        })
                      }
                    >
                      −
                    </button>
                    <span>{it.qty}</span>
                    <button
                      type="button"
                      className="h-[26px] w-[26px] border-2"
                      style={{ borderColor: "var(--ink)", borderRadius: 2 }}
                      onClick={() => add(it.id)}
                    >
                      +
                    </button>
                  </div>
                  <button
                    type="button"
                    className="mono mt-2 text-[0.62rem] uppercase"
                    style={{ color: "var(--mart-muted)", letterSpacing: "0.1em" }}
                    onClick={() =>
                      setCart((c) => {
                        const n = { ...c };
                        delete n[it.id];
                        return n;
                      })
                    }
                  >
                    REMOVE
                  </button>
                </div>
                <div className="mono text-right text-[0.9rem] font-bold">
                  {money(it.priceUsd * it.qty)}
                </div>
              </div>
            ))
          )}
        </div>
        <div className="border-t-2 px-6 py-5" style={{ borderColor: "var(--ink)" }}>
          <div className="mono mb-4 flex justify-between text-[1rem] font-bold">
            <span>TOTAL</span>
            <span>{money(total)}</span>
          </div>
          <button
            type="button"
            onClick={openCheckout}
            className="mono w-full border-2 py-4 text-[0.85rem] font-bold uppercase transition hover:bg-[var(--ink)] hover:text-[var(--mart-accent)]"
            style={{
              background: "var(--mart-accent)",
              color: "var(--ink)",
              borderColor: "var(--ink)",
              letterSpacing: "0.15em",
              borderRadius: 2,
            }}
          >
            CHECKOUT ↗
          </button>
        </div>
      </aside>

      {/* Checkout modal */}
      {coOpen && (
        <div
          className="fixed inset-0 z-[90] flex items-center justify-center p-4"
          style={{
            background: "rgba(20,20,20,.55)",
            backdropFilter: "blur(8px)",
          }}
          onClick={(e) => {
            if (e.target === e.currentTarget) setCoOpen(false);
          }}
        >
          <div
            className="relative max-h-[92vh] w-[min(560px,96vw)] overflow-y-auto border-2 p-8"
            style={{
              background: "var(--paper)",
              borderColor: "var(--ink)",
              borderRadius: 3,
            }}
          >
            <button
              type="button"
              className="absolute right-4 top-4 text-2xl"
              onClick={() => setCoOpen(false)}
            >
              ×
            </button>

            {step === "main" && (
              <>
                <div className="text-[1.7rem] font-black uppercase tracking-tight">
                  Checkout
                </div>
                <div
                  className="mono mb-6 text-[0.72rem] uppercase"
                  style={{ color: "var(--mart-muted)", letterSpacing: "0.1em" }}
                >
                  SETTLEMENT: MONAD TESTNET · INSTANT
                </div>
                <div
                  className="mono mb-4 border-2 bg-white p-4 text-[0.78rem] leading-relaxed"
                  style={{ borderColor: "var(--ink)", borderRadius: 2 }}
                >
                  {items.map((i) => (
                    <div key={i.id}>
                      {i.qty} × {i.name.toUpperCase()} —{" "}
                      {money(i.priceUsd * i.qty)}
                    </div>
                  ))}
                </div>
                <div
                  className="mono mb-8 flex justify-between border-t-2 pt-3 text-[1.05rem] font-bold"
                  style={{ borderColor: "var(--ink)" }}
                >
                  <span>TOTAL DUE</span>
                  <span>{money(total)}</span>
                </div>

                <div
                  className="mono mb-3 text-[0.68rem] uppercase"
                  style={{ letterSpacing: "0.18em", color: "var(--mart-muted)" }}
                >
                  WHO IS PAYING?
                </div>
                <div className="mb-6 grid grid-cols-2 gap-4 max-md:grid-cols-1">
                  <button
                    type="button"
                    onClick={() => setWho("human")}
                    className="mono border-2 p-6 text-[1rem] font-bold uppercase"
                    style={{
                      borderColor: "var(--ink)",
                      borderRadius: 2,
                      letterSpacing: "0.15em",
                      background: who === "human" ? "var(--ink)" : "#fff",
                      color: who === "human" ? "var(--paper)" : "var(--ink)",
                    }}
                  >
                    HUMAN
                    <small
                      className="mt-1 block text-[0.6rem] font-normal"
                      style={{
                        letterSpacing: "0.1em",
                        opacity: 0.7,
                      }}
                    >
                      CARD PAYMENT
                    </small>
                  </button>
                  <button
                    type="button"
                    onClick={() => setWho("agent")}
                    className="mono border-2 p-6 text-[1rem] font-bold uppercase"
                    style={{
                      borderColor: "var(--ink)",
                      borderRadius: 2,
                      letterSpacing: "0.15em",
                      background:
                        who === "agent" ? "var(--mart-accent)" : "#fff",
                      color: "var(--ink)",
                    }}
                  >
                    AGENT
                    <small
                      className="mt-1 block text-[0.6rem] font-normal"
                      style={{ letterSpacing: "0.1em", opacity: 0.7 }}
                    >
                      TOKEN PAYMENT
                    </small>
                  </button>
                </div>

                {who === "human" && (
                  <div
                    className="mb-4 border-2 bg-white p-5"
                    style={{ borderColor: "var(--ink)", borderRadius: 2 }}
                  >
                    <label
                      className="mono mb-2 block text-[0.65rem] uppercase"
                      style={{
                        letterSpacing: "0.15em",
                        color: "var(--mart-muted)",
                      }}
                    >
                      CARDHOLDER NAME
                    </label>
                    <input
                      className="mono mb-4 w-full border-2 px-4 py-3 outline-none"
                      style={{
                        background: "var(--paper)",
                        borderColor: "var(--ink)",
                        borderRadius: 2,
                      }}
                      value={humanName}
                      onChange={(e) => setHumanName(e.target.value)}
                    />
                    <label
                      className="mono mb-2 block text-[0.65rem] uppercase"
                      style={{
                        letterSpacing: "0.15em",
                        color: "var(--mart-muted)",
                      }}
                    >
                      CARD NUMBER (DEMO)
                    </label>
                    <input
                      className="mono mb-4 w-full border-2 px-4 py-3 outline-none"
                      style={{
                        background: "var(--paper)",
                        borderColor: "var(--ink)",
                        borderRadius: 2,
                      }}
                      defaultValue="4242 4242 4242 4242"
                    />
                    <button
                      type="button"
                      onClick={payHuman}
                      className="mono w-full border-2 py-4 text-[0.82rem] font-bold uppercase"
                      style={{
                        background: "var(--ink)",
                        color: "var(--paper)",
                        borderColor: "var(--ink)",
                        letterSpacing: "0.15em",
                        borderRadius: 2,
                      }}
                    >
                      PAY NOW ↗
                    </button>
                  </div>
                )}

                {who === "agent" && (
                  <div
                    className="border-2 bg-white p-5"
                    style={{ borderColor: "var(--ink)", borderRadius: 2 }}
                  >
                    <form onSubmit={verifyToken}>
                      <label
                        className="mono mb-2 block text-[0.65rem] uppercase"
                        style={{
                          letterSpacing: "0.15em",
                          color: "var(--mart-muted)",
                        }}
                      >
                        PASTE AGENT ACCESS TOKEN
                      </label>
                      <input
                        className="mono mb-4 w-full border-2 px-4 py-3 outline-none"
                        style={{
                          background: "var(--paper)",
                          borderColor: "var(--ink)",
                          borderRadius: 2,
                        }}
                        placeholder="MAP_XXXX-XXXX-XXXX-XXXX"
                        value={tokenInput}
                        onChange={(e) => setTokenInput(e.target.value)}
                      />
                      <button
                        type="submit"
                        className="mono w-full border-2 py-4 text-[0.82rem] font-bold uppercase"
                        style={{
                          background: "var(--ink)",
                          color: "var(--paper)",
                          borderColor: "var(--ink)",
                          letterSpacing: "0.15em",
                          borderRadius: 2,
                        }}
                      >
                        ENTER ↵
                      </button>
                    </form>
                    {testTokens.length > 0 && (
                      <div
                        className="mono mt-4 text-[0.66rem] leading-loose"
                        style={{ color: "var(--mart-muted)" }}
                      >
                        ACTIVE TOKENS (CLICK TO FILL):
                        <br />
                        {testTokens.map((t) => (
                          <button
                            key={t.tokenString}
                            type="button"
                            className="mr-2 underline"
                            style={{ color: "var(--ink)" }}
                            onClick={() => setTokenInput(t.tokenString)}
                          >
                            {t.tokenString}
                          </button>
                        ))}
                      </div>
                    )}
                    {tokenErr && (
                      <div
                        className="mono mt-3 text-[0.75rem] font-bold"
                        style={{ color: "var(--err)", letterSpacing: "0.06em" }}
                      >
                        {tokenErr}
                      </div>
                    )}
                    {ownerName && (
                      <div
                        className="mt-4 border-2 p-5 text-center"
                        style={{
                          borderColor: "var(--mart-accent)",
                          background: "var(--paper)",
                          borderRadius: 2,
                        }}
                      >
                        <div
                          className="mono mb-2 text-[0.62rem] uppercase"
                          style={{
                            letterSpacing: "0.2em",
                            color: "var(--mart-muted)",
                          }}
                        >
                          AUTHORIZED PAYER — NAME ONLY
                        </div>
                        <div className="mb-4 text-[1.6rem] font-black uppercase tracking-tight">
                          {ownerName}
                        </div>
                        <button
                          type="button"
                          onClick={payAgent}
                          className="mono w-full border-2 py-4 text-[0.82rem] font-bold uppercase"
                          style={{
                            background: "var(--mart-accent)",
                            color: "var(--ink)",
                            borderColor: "var(--ink)",
                            letterSpacing: "0.15em",
                            borderRadius: 2,
                          }}
                        >
                          AUTHORIZE PAYMENT
                        </button>
                      </div>
                    )}
                  </div>
                )}
              </>
            )}

            {step === "processing" && (
              <div
                className="mono py-12 text-center text-[0.9rem] uppercase"
                style={{ letterSpacing: "0.2em" }}
              >
                SETTLING ON MONAD
                <span className="inline-block animate-[blink_1s_steps(2)_infinite]">
                  …
                </span>
              </div>
            )}

            {step === "success" && (
              <div className="py-4 text-center">
                <div
                  className="mx-auto mb-5 flex h-16 w-16 items-center justify-center rounded-full border-2 text-3xl"
                  style={{
                    background: "var(--mart-accent)",
                    borderColor: "var(--ink)",
                    animation: "pop .5s cubic-bezier(.16,1,.3,1)",
                  }}
                >
                  ✓
                </div>
                <div className="mb-2 text-[2rem] font-black uppercase tracking-tight">
                  Payment Successful
                </div>
                <div
                  className="mono mb-6 text-[0.75rem] uppercase leading-loose"
                  style={{ color: "var(--mart-muted)", letterSpacing: "0.08em" }}
                  dangerouslySetInnerHTML={{ __html: successMeta }}
                />
                <div
                  className="mb-4 border-2 bg-white p-5 text-left"
                  style={{ borderColor: "var(--ink)", borderRadius: 2 }}
                >
                  <div className="mono mb-3 flex justify-between text-[0.68rem] uppercase">
                    <span>INVOICE GENERATED</span>
                    <span
                      className="border-2 px-2 font-bold"
                      style={{
                        background: "var(--mart-accent)",
                        borderColor: "var(--ink)",
                      }}
                    >
                      PDF
                    </span>
                  </div>
                  <div className="mono mb-4 break-all text-[0.85rem] font-bold">
                    {invId}
                  </div>
                  {txHash && (
                    <a
                      className="mono mb-3 block text-[0.7rem] underline"
                      href={`https://testnet.monadvision.com/tx/${txHash}`}
                      target="_blank"
                      rel="noreferrer"
                    >
                      View Monad tx →
                    </a>
                  )}
                  <div className="grid grid-cols-2 gap-3 max-md:grid-cols-1">
                    <button
                      type="button"
                      className="mono border-2 py-3 text-[0.7rem] font-bold uppercase"
                      style={{
                        background: "var(--mart-accent)",
                        borderColor: "var(--ink)",
                        letterSpacing: "0.12em",
                        borderRadius: 2,
                      }}
                      onClick={() => {
                        const a = document.createElement("a");
                        a.href = invBlobUrl;
                        a.download = invId;
                        a.click();
                      }}
                    >
                      DOWNLOAD PDF
                    </button>
                    <button
                      type="button"
                      className="mono border-2 py-3 text-[0.7rem] font-bold uppercase"
                      style={{
                        background: "var(--paper)",
                        borderColor: "var(--ink)",
                        letterSpacing: "0.12em",
                        borderRadius: 2,
                      }}
                      onClick={() => {
                        const payload = `INVOICE ${invId} | ORDER ${orderId} | TOTAL ${money(total)}\n${invDataUrl}`;
                        navigator.clipboard?.writeText(payload);
                      }}
                    >
                      COPY TO AGENT
                    </button>
                  </div>
                </div>
                <p
                  className="mono mb-4 text-[0.66rem] uppercase leading-relaxed"
                  style={{ color: "var(--mart-muted)", letterSpacing: "0.08em" }}
                >
                  INVOICE HANDED TO AGENT. AGENT DELIVERS PDF TO OWNER.
                </p>
                <button
                  type="button"
                  className="mono w-full border-2 py-3 text-[0.7rem] font-bold uppercase"
                  style={{ borderColor: "var(--ink)", borderRadius: 2 }}
                  onClick={() => setCoOpen(false)}
                >
                  DONE
                </button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
