export const agentPayVaultAbi = [
  {
    type: "function",
    name: "topUp",
    stateMutability: "payable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "grantPermission",
    stateMutability: "nonpayable",
    inputs: [
      { name: "agent", type: "address" },
      { name: "amountLimit", type: "uint256" },
      { name: "category", type: "string" },
      { name: "allowedWebsites", type: "string[]" },
      { name: "expiry", type: "uint256" },
      { name: "singleUse", type: "bool" },
    ],
    outputs: [{ name: "policyId", type: "bytes32" }],
  },
  {
    type: "function",
    name: "spend",
    stateMutability: "nonpayable",
    inputs: [
      { name: "policyId", type: "bytes32" },
      { name: "merchant", type: "address" },
      { name: "amount", type: "uint256" },
      { name: "category", type: "string" },
      { name: "website", type: "string" },
      { name: "orderId", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "revokePermission",
    stateMutability: "nonpayable",
    inputs: [{ name: "policyId", type: "bytes32" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawAll",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "vaultBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getPolicy",
    stateMutability: "view",
    inputs: [{ name: "policyId", type: "bytes32" }],
    outputs: [
      { name: "agent", type: "address" },
      { name: "amountLimit", type: "uint256" },
      { name: "spent", type: "uint256" },
      { name: "category", type: "string" },
      { name: "allowedWebsites", type: "string[]" },
      { name: "expiry", type: "uint256" },
      { name: "singleUse", type: "bool" },
      { name: "used", type: "bool" },
      { name: "active", type: "bool" },
    ],
  },
  {
    type: "function",
    name: "remainingAllowance",
    stateMutability: "view",
    inputs: [{ name: "policyId", type: "bytes32" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "event",
    name: "PermissionGranted",
    inputs: [
      { name: "policyId", type: "bytes32", indexed: true },
      { name: "agent", type: "address", indexed: true },
      { name: "amountLimit", type: "uint256", indexed: false },
      { name: "category", type: "string", indexed: false },
      { name: "expiry", type: "uint256", indexed: false },
      { name: "singleUse", type: "bool", indexed: false },
    ],
  },
  {
    type: "event",
    name: "PaymentAuthorized",
    inputs: [
      { name: "policyId", type: "bytes32", indexed: true },
      { name: "agent", type: "address", indexed: true },
      { name: "merchant", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "category", type: "string", indexed: false },
      { name: "website", type: "string", indexed: false },
      { name: "orderId", type: "string", indexed: false },
    ],
  },
  { type: "error", name: "NotOwner", inputs: [] },
  { type: "error", name: "NotAgent", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  { type: "error", name: "InsufficientVaultBalance", inputs: [] },
  { type: "error", name: "PolicyNotFound", inputs: [] },
  { type: "error", name: "PolicyInactive", inputs: [] },
  { type: "error", name: "PolicyExpired", inputs: [] },
  { type: "error", name: "PolicyAlreadyUsed", inputs: [] },
  { type: "error", name: "AmountLimitExceeded", inputs: [] },
  { type: "error", name: "CategoryNotAllowed", inputs: [] },
  { type: "error", name: "MerchantNotAllowed", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
  { type: "error", name: "Reentrancy", inputs: [] },
  { type: "error", name: "EmptyCategory", inputs: [] },
  { type: "error", name: "EmptyAllowlist", inputs: [] },
] as const;

export const monadTestnet = {
  id: 10143,
  name: "Monad Testnet",
  nativeCurrency: { name: "MON", symbol: "MON", decimals: 18 },
  rpcUrls: {
    default: { http: ["https://testnet-rpc.monad.xyz"] },
  },
  blockExplorers: {
    default: { name: "MonadVision", url: "https://testnet.monadvision.com" },
  },
} as const;
